### ISSUE TITLE
Feature: improve txzchk to use the new table-driven walk code

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#1325]
### Is there an existing issue for this?

- [x] I have searched for existing issues and did not find anything like this

### Describe the enhancement

With commit a901495217f5b8273d8b0eab080a61dc5f561e4c, "_table driven walk code_" has been added to the repo.

## Overview

The recently added "_new table driven walk code_" is found in:

- soup/walk.h
- soup/walk_tbl.c
- soup/walk_util.c

Test code that exercises the "_new table driven walk code_" is found in:

- test_ioccc/try_walk_set.c
- test_ioccc/try_fts_walk.c

The above 2 programs should be viewed as examples and demos of the "_table driven walk code_".

The actual tables in the "_table driven walk code_" are found in `soup/walk_tbl.c`.

Important and **general toolkit purpose** "_table driven walk
code_" macros, definitions, and related data structures are found in
`soup/walk.h`.

## On soup/walk.h and soup/walk_util.c

Important and ** general toolkit purpose** "_table driven walk code_"
functions are found in `soup/walk_util.c`.

We have no doubt that the "_table driven walk code_" is just a general
API, **AND** that there may be special services that this particular
tool requires.

**PLEASE**: Please keep the contents of `soup/walk.h` and
`soup/walk_util.c` for **general toolkit purpose** and **NOT** for
something specific to this particular tool.

## On soup/walk_tbl.c

The contents of `soup/walk_tbl.c` were formed on the basis of
[GH issuecomment-3240531487](https://github.com/ioccc-src/mkiocccentry/issues/1297#issuecomment-3240531487),
with a few modifications.

The contents of `soup/walk_tbl.c` represent a new **IOCCC29 policy** and
should **NOT** be changed lightly: although we acknowledge some minor
tweaking may be needed.  We **DO** acknowledge that incorporating the
contents of `soup/walk_tbl.c` in this toolkit will produce an environment
that is **DIFFERENT** from what was in place for **IOCCC28**.   Most of
those changes are **deliberate**.

If you do find a need to modify the contents of `soup/walk_tbl.c`,
beyond fixing typos and improving comments, **PLEASE** discuss the idea
in a comment before modifying where reassemble.

## Recommended actions

This tool needs to be modified so that it uses the new "_table-driven
walk code_", replacing hard-coded logic that this tool currently uses.
Each tool has its own `struct walk_rule` (and in the case of `chkentry(1)`
several depending on command-line flags) that should be initialized and
used by the tool.

Please update the test suite in this toolkit to test the effects of
the new "_table-driven walk code_".  In doing so, you have to find certain
surprising changes to the behavior of this tool.  As mentioned above in
the section on "_On soup/walk_tbl.c_", some of those changes represent a
new **IOCCC29 policy**, although there may be "_mis-features_" as well.
Feel free to discuss any test result changes that seem "_wrong_" or
at least seem "_undesirable_", in comments below before attempting to
modify the tables.

If you do need to add something "_specific_" to the "_table-driven
walk code_" on behalf of this tool, **please** consider adding those
"_specifics_" to this tool's `TOOLNAME.c` and `TOOLNAME.h` files,
**OR** if there is a lot of specific stuff, consider adding a new
`soup/walk_TOOLNAME.c` and `soup/walk_TOOLNAME.h` instead.  Keep the
contents of `soup/walk.h` and `soup/walk_util.c` general, if at all
possible.

For example, the output from the `chk_walk()` function may not be
completely suitable for this specific tool, and this tool may need/wish
to report problems in a way that improves the understanding of someone
submitting to the contest.  In such a case, pass `NULL` as the `stream`
arg to the `chk_walk()` function (to silence such messages from the
`chk_walk()` function), and write new tool-specific functions that
reach into and report on the contest’s `struct walk_rule` after the
`chk_walk()` function returns `false`.  Such code should be added to
either the tool's `TOOLNAME.c` and `TOOLNAME.h` files, **OR** to some
new `soup/walk_TOOLNAME.c` and `soup/walk_TOOLNAME.h` instead.

Feel free, after studying the above, to question, comment, and suggest
as needed.

### Relevant images, screenshots or other files

- soup/walk.h
- soup/walk_tbl.c
- soup/walk_util.c
- test_ioccc/try_walk_set.c
- test_ioccc/try_fts_walk.c

### Relevant links

- commit a901495217f5b8273d8b0eab080a61dc5f561e4c
- [GH issuecomment-3240531487](https://github.com/ioccc-src/mkiocccentry/issues/1297#issuecomment-3240531487)

## Old code cleanup

Once this issue for this, as well as related issues for the other major
tools in this toolkit are completed, the old hard-coded logic functions,
macros, definitions, and related data structures need to be removed from
the repo.    While not a complete identification, some of the old hard
coded source code may be identified by comments such as:

```c
/* XXX - pre-IOCCC29: remove the obsolete function below - XXX */
/* XXX - pre-IOCCC29: remove the obsolete #if block below - XXX */
/* XXX - pre-IOCCC29: remove the obsolete #if block above - XXX */
/* XXX - pre-IOCCC29: remove the obsolete ifdef block below - XXX */
/* XXX - pre-IOCCC29: remove the obsolete ifdef block above - XXX */
/* XXX - remove after table driven walk code is in place - XXX */
etc.
```

## See also

- [improve mkiocccentry to use the new table-driven walk code](https://github.com/ioccc-src/mkiocccentry/issues/1324)
- [improve txzchk to use the new table-driven walk code](https://github.com/ioccc-src/mkiocccentry/issues/1325)
- [improve chkenty and chksubmit to use the new table-driven walk code](https://github.com/ioccc-src/mkiocccentry/issues/1326)

**Comment by lcn2** [comment]
This issue was closed as accident.  It has been re-opened.

**Comment by xexyl** [comment]
I will try looking at it in more detail tomorrow. But if not then hopefully the weekend. 

Leaving again for the day.

**Comment by lcn2** [comment]
> # QUESTION
> 
> Okay I have not studied the walking code yet (too tired to do so) but to be sure I get this right: I only need to replace the functions that have the XXX comments?

We made a guess as to the extent of the old code that needs to be removed.   But that is just a guess.   Be sure to check for the "_XXX_"'s throughout the code base, and be prepared to have to remove more than what was initially identified.

> If that is so I guess this tool will be easier to deal with than (I suspect) the other ones. I was hopeful of this for a variety of reasons and I couldn't imagine how it could be anything else than simple as txzchk parses output from tar(1) and does not strictly walk as such.

Likely, yes.

> I also guess that the test suite is not going to be changed in this tool for the same reason (it seems like - I have not checked the other issues opened - that the issue description are the same)?

The output for the tool may change in terms of feather counts.  For example, certain path cases that were avoided may now be permitted.   Moreover how files and directories are counted changed, so there may be edge test cases that need to change.  You may wish to add more test cases given path canonicalization.  However the general test methodology of the `txzchk(1)` is likely to be similar.

**Comment by lcn2** [comment]
> Okay studying the code a bit (eyes bleary though) .. looking at try_fts_walk.c and I see something I wonder very much about:
> 
> ```c
>         /* test walk_set WALK_SET_TXZCHK */
>         walk_ok = test_walk(stdout,
>                             topdir, &walk_txzchk, "txzchk",
>                             max_path_len, max_filename_len, max_depth,
>                             max_file, max_dir, max_sym, max_other,
>                             sort_cpath);
> ```
> 
> Okay but txzchk uses a tarball listing - it obviously doesn't use fts(3). But test_walk() uses, it would appear, `fts_walk()`, which itself uses the `fts(3)` API. I do see of course in the `struct walk_stat` the boolean `tar_listing_used` which suggests it does not always use `fts(3)`. But that function does anyway, `fts_walk()`, as you'd expect from the name.
> 
> But that boolean is not really used: it's used for debug output and it's set to false. 
> 
> Also `topdir` has to be != NULL but that's not relevant for txzchk. It is for mkiocccentry and chkentry - as I put it there of course though the walk code was done differently of course (with some remnants of it still here but a new set of structs and other things).
> 
> But the fact txzchk does not walk a tree is what is confusing me. This does change things, this confusion. Should we expand it to work on strings if that boolean is true? If that's an idea you like I can try and look at it hopefully by Sunday. I haven't looked beyond this and I can't now but hopefully this will be a good start.
> 
> 

The `test_walk()` function isn't the approach you should consider for `txzchk(1)`: especially because the `txzchk(1)` isn't walking a directory tree.  We will post a new comment later on that should guide you into a more productive direction.

In the mean time, as mentioned elsewhere:

"We have a new service function to add to the walk code that will be helpful with your work on txzchk(1) that we hope to commit later today."

... but first we have to "fully wake up this morning", interact with some important house guests, and then help carry a newly completed harpsichord that my brother made from the woodshop into the main room .. in between periods of rain this noon.

Stay tuned for further developments.

**Comment by xexyl** [comment]
> > Okay studying the code a bit (eyes bleary though) .. looking at try_fts_walk.c and I see something I wonder very much about:
> >         /* test walk_set WALK_SET_TXZCHK */
> >         walk_ok = test_walk(stdout,
> >                             topdir, &walk_txzchk, "txzchk",
> >                             max_path_len, max_filename_len, max_depth,
> >                             max_file, max_dir, max_sym, max_other,
> >                             sort_cpath);
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Okay but txzchk uses a tarball listing - it obviously doesn't use fts(3). But test_walk() uses, it would appear, `fts_walk()`, which itself uses the `fts(3)` API. I do see of course in the `struct walk_stat` the boolean `tar_listing_used` which suggests it does not always use `fts(3)`. But that function does anyway, `fts_walk()`, as you'd expect from the name.
> > But that boolean is not really used: it's used for debug output and it's set to false.
> > Also `topdir` has to be != NULL but that's not relevant for txzchk. It is for mkiocccentry and chkentry - as I put it there of course though the walk code was done differently of course (with some remnants of it still here but a new set of structs and other things).
> > But the fact txzchk does not walk a tree is what is confusing me. This does change things, this confusion. Should we expand it to work on strings if that boolean is true? If that's an idea you like I can try and look at it hopefully by Sunday. I haven't looked beyond this and I can't now but hopefully this will be a good start.
> 
> The `test_walk()` function isn't the approach you should consider for `txzchk(1)`: especially because the `txzchk(1)` isn't walking a directory tree. We will post a new comment later on that should guide you into a more productive direction.
> 

That was my confusion indeed. It seemed odd that the functions had reference to reading output of tar(1) for this reason.

> In the mean time, as mentioned elsewhere:
> 
> "We have a new service function to add to the walk code that will be helpful with your work on txzchk(1) that we hope to commit later today."
> 

> ... but first we have to "fully wake up this morning", interact with some important house guests, and then help carry a newly completed harpsichord that my brother made from the woodshop into the main room .. in between periods of rain this noon.
> 
> Stay tuned for further developments.

I'll check probably tomorrow morning (but maybe not do anything with it until at least Saturday).

Thanks.

**Comment by lcn2** [comment]
FYI: We plan to address some of the questions above.  In the mean time, see:

[GH issuecomment-3438921986](https://github.com/lcn2/cpath/pull/4#issuecomment-3438921986)

We also plan to write a comment with some suggestions specific to `txzchk(1)` later today.

**Comment by xexyl** [comment]
I can't read in details until probably at least until tomorrow. 

However I do have a big concern here. 

The tool does much more than just record the number of files and checking those files. 

In other words it does much more than just reading in each line. 

From what I (admittedly probably not enough) see there this will not suffice. 

Will this record (to check) uid/gid for example? What about permissions (to check)? Other things too. These are important things that are not actually files. 

Also what about BSD versus Linux tar output? 

It certainly won't populate the struct which keeps track of a lot of details. 

Just having a single function call cannot suffice here unless you want to make the code not as robust or you want to seriously reduce the number of restrictions. 

Again unless I have missed something which is I suppose possible. 

Please advise. I will check another day. Probably tomorrow if I at all can.

**Comment by lcn2** [comment]
>    ...
>         read a line from the tarball listing
>         set path from the tarball listing line
>         set st_size to the file size from the tarball listing line
>         set st_mode in stat(2) form, from the tarball listing line
>     ...
> 
>     /* process the path, size, and st_mode from the tarball listing line */
>     processed = record_step(&wstat, path, path, st_size, st_mode, &dup, &cpath);
>     if (dup) {

Notice the above.

You have to read the line from the tarball listing (and thus know if it is a BSD or Linux tarball style listing), extract the size (in the form of an st_size) and file type (in the form of an st_mode).  Once you have that from a tarball listing line, then call `record_step()`.

Meanwhile with that tarball listing line you have to do other stuff such as verify the tarball listing doesn't give away usernames, etc.  All that the "table-driven walk code" is doing is keep track of the filename inventory.

At the end of the tarball listing, when you call `chk_walk()` verify the completed inventory (file and directory counts, what is required, what is optional, what must be non-zero in size, what is prohibited, etc.).

The tool still has to do the other tasks that it does now.

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by lcn2** [comment]
See also [GH issuecomment-3448047128](https://github.com/ioccc-src/mkiocccentry/issues/1324#issuecomment-3448047128).

**Comment by lcn2** [comment]
> I was about to start the removal of the files linked lists but then something dawned on me.
> 
> One of the purposes of this (not the main purpose) was to have statistics about the tarball. Now it also did other checks but I could still have statistics like what size the Makefile is etc.
> 
> Now that might or might not be worth it. 

It is probably not worth it ...

> I don't know. But before I remove that linked list I want to make sure to have your thoughts. I know that I'm probably the only one who ever made use of that but in case you have some need or want...

After the `chk_walk()` call and before the `free_walk_stat()` call, the `show_tarball_info()` function could do things such as:

```c
    struct walk_stat wstat;    /* struct walk_stat */
    struct item *i_p;       /* pointer to an element in the dynamic array */
    intmax_t len;                       /* number of elements in the dynamic array */

    ...

    i_p = path_in_walk_stat(&wstat, "Makefile");
    if (i_p == NULL) {
        dbg(DBG_MED, "%s does not have a Makefile", tarball_path);
    } else if (_p->st_size == 0) {
        dbg(DBG_HIGH, "%s has an empty Makefile", tarball_path);
    } else {
        dbg(DBG_HIGH, "%s Makefile size is %lld", (long long) i_p->st_size);
    }

    ...

    dbg(DBG_MED, "%s has a total of %ju directory depth error(s)",
        tarball_path, dyn_array_tell(wstat.too_deep));
    dbg(DBG_MED, "%s has %ju required filename(s)",
        tarball_path, dyn_array_tell(wstat.required));

    ...
```

However the debug output of `show_tarball_info()` was never used.  So while all of the debug data needed for the `show_tarball_info()` function is there in a `structure walk_stat`, the fact that it was never used suggests coding it might not be worth the effort.

> What debug information do you think should stay put?

The total size of the tarball contents might be useful at the `-v 1` (DBG_LOW) level. 

The total sum can computed by summing up the sizes parsed from the tarball listing.   You have the size from when you parse the tarball listing as you need to supply that value as the `st_size` arg to the `record_step()` function, so you might as well just sum those values and report their sum.

You have to compute the sum of the byte lengths of all files in order to compare against `MAX_SUM_FILELEN`, so you might as well report it via `dbg(DBG_LOW, ...);`.

> What debug information do you think should stay put? If it helps you can look at the struct tarball. Clearly some of it has to be removed (or at least is not needed). My belief is actually that almost every single member can be removed.

The entire `struct tarball` is not needed.

**Comment by xexyl** [comment]
`sum_and_count()` related code is gone from txzchk and soup/util.

This brings up another question though - for the OT thread ... will do that now and then proceed with what I'm working on (at least that is my plan at this precise moment).

**Comment by xexyl** [comment]
There is a very weird bug either with fnamchk or txzchk ... not sure what yet ... looking into it as it's causing me a problem. I'm also not sure if the fact some code was removed and not yet finished is why some other problem I have encountered. But since it reports an issue and still does not exit non-zero ...

**Comment by xexyl** [comment]
Something is very wrong .. might have to open a new bug report ... and I haven't the slightest clue what is going on. It is a problem though for the test suite.

**Comment by xexyl** [comment]
Okay I think I almost have it but one thing (okay some things) is (are) not clear to me. When recording the path do you plan on having the full path? Because in some cases this might be needed with subdirectories. However when having for example `test-0/Makefile` it does not see it as existing.

This also seems odd...

```
txzchk required: Makefile not found
txzchk required: prog.c not found
txzchk required: remarks.md not found
txzchk required: .auth.json not found
txzchk required: .info.json not found
txzchk found 2 prohibited items
   prohibited file: test-0/.auth.json
   prohibited file: test-0/.info.json
```

But the directory has to be there to satisfy fnamchk. The full path is there but somehow it's saying the two dot files that are required are prohibited.

So what am I missing? Once you clarify what you need I can finish it (I hope). In the meantime I'm going to do other things and might be done for the day.

Hope you are having a brilliant birthday!

**Comment by xexyl** [comment]
BTW: I had to change `cpath_ret` to not be `const char **` (just `char **`) as the caller has to free it. So that routine has been updated in that way too.

Doing other things now.

**Comment by lcn2** [comment]
> **IMPORTANT** note for you [@lcn2](https://github.com/lcn2):
> 
> I hope you see commit [d639398](https://github.com/ioccc-src/mkiocccentry/commit/d639398c0e2e6b23849a1e9e46c8878e48be392f) before you start working on the walk code updates as I have some fixes. This solves some of the issues I was running into with the updates here but not all. I'll wait for you on that.
> 
> If there are conflicts with your changes, which I suppose is not at all unlikely, I can either fix them OR I can redo it after you've made the changes.

We will work on a merge.  Stay tuned.

**Comment by lcn2** [comment]
> I might be wrong but it seems like there are some issues with the walk routine in concept when it comes to txzchk wrt directory required and required dot files.
> 
> For some files it seems like possibly (didn't test this or look into it deeply) the basename is needed. But this presents a problem in that the files that this matters would have to be hard code checked. And for others like `.info.json` and `.auth.json` it seems to want to prohibit them.
> 
> The first one: files are not found it seems possibly due to the path. I guess the second part is that any dot file in any directory is being marked as prohibited.

We believe you are incorrect.

The `.info.json` and `.auth.json` files are created by `mkiocccentry(1)` and thus are **required**, must be **non-empty**, and are **free** (i.e., does not count towards the file count limit).  In `soup/walk_tbl.c`, the `walk_rule_set_txzchk[]` array contains:

```c
    /*
     * .auth.json
     *
     * This file is created by the mkiocccentry tool.
     *
     * Regarding types: We match files only and let "((anything))" rule below deal with any other
     *                  types to avoid "funny business" (as the expression goes).
     */
    { ".auth.json",
        true, true, true, false, false,                 /* required, non-empty, free */
        MATCH_STR_ANYCASE, TYPE_FILE, LEVEL_TOP,        /* match whole string any case, file type, at top level only */
        0, NULL },

    /*
     * .info.json
     *
     * This file is created by the mkiocccentry tool.
     *
     * Regarding types: We match files only and let "((anything))" rule below deal with any other
     *                  types to avoid "funny business" (as the expression goes).
     */
    { ".info.json",
        true, true, true, false, false,                 /* required, non-empty, free */
        MATCH_STR_ANYCASE, TYPE_FILE, LEVEL_TOP,        /* match whole string any case, file type, at top level only */
        0, NULL },
```

Later in that same `walk_rule_set_txzchk[]` array, we have two entries that prevent a **non-file** (e.g., a directory to symlink) from using the name `.info.json` and `.auth.json`:

```c
    /*
     * .auth.json ((not a file))
     *
     * This file is created by the mkiocccentry tool.
     *
     * Regarding types: We match anything that is NOT a file.
     */
    { ".auth.json",
        false, false, false, false, true,               /* prohibited */
        MATCH_STR_ANYCASE, TYPE_NOT_FILE, LEVEL_TOP,    /* match whole string any case, not file type, at top level only */
        0, NULL },

    /*
     * .info.json ((not a file))
     *
     * This file is created by the mkiocccentry tool.
     *
     * Regarding types: We match anything that is NOT a file.
     */
    { ".info.json",
        false, false, false, false, true,               /* prohibited */
        MATCH_STR_ANYCASE, TYPE_NOT_FILE, LEVEL_TOP,    /* match whole string any case, not file type, at top level only */
        0, NULL },
```

Now the . (dot) directory, if found, is **optional** (i.e., **NOT required**), **NOT empty**, **free** ((i.e., does not count towards the file count limit), should the . (dot) directory be given, will do nothing:

```c
    /*
     * . ((dot))
     *
     * In case the tree walking or tarball list functions encounter a "." (dot) directory, we ignore it.
     *
     * This will mean that the ".*" (dot star) walk_rule below will not match any "." (dot) directory.
     *
     * Regarding types: We match directories only and let "((anything))" rule below deal with any other
     *                  types to avoid "funny business" (as the expression goes).
     */
    { ".",
        false, false, true, true, false,                /* optional, free, ignore */
        MATCH_STR, TYPE_DIR, LEVEL_ANY,                 /* match whole string, directory, at any level */
        0, NULL },
```

Then anything else that starts with  . ((dot)) is **prohibited**:

```c
   /*
     * .* (dot star)
     *
     * The mkiocccentry tool creates a select set of ".*" (dot star) files that are managed by walk_rule entries
     * above, therefore the mkiocccentry tool checks should have prevented other ".*" (dot star) items.
     * We match is again, in case of "funny business" (as the expression goes) involving attempts to bypass checks
     * made by the mkiocccentry tool, and in case the tarball has been modified after formation.
     *
     * NOTE: ".." (dot-dot) is processed first in this struct walk_rule array, and the directory "." (dot)
     *       is processed above.
     *
     * Regarding types: We match any type, not just files, to avoid "funny business" (as the expression goes).
     */
    { ".",
        false, false, false, false, true,               /* prohibited */
        MATCH_PREFIX, TYPE_ANY, LEVEL_ANY,              /* match beginning, any type, at any level */
        0, NULL },
```

**IMPORTANT**: The comment reads `.* (dot star)` because the comment indicates that the . (dot) is a **PREFIX**.  This is why the above `struct walk_rule` uses **MATCH_PREFIX**.  So `.foo`, `.git`, `.github` all match because they all start with the . (dot) prefix/

The `test_ioccc/try_walk_set` tool, and the `test_ioccc/try_fts_walk` tool will help you determine what the tables are doing.  For testing under `txzchk(1)` tables, use `-s 2`.

Try:

```sh
$ cat > foo <<EOF
f 1234 prog.c
f 2345 Makefile
f 3456 remarks.md
f 246 .info.json
f 357 .auth.json
EOF

$ test_ioccc/try_walk_set -s 2 -v 3 < foo
```

Then try:

```sh
$ cp -f foo bar

$ cat >>bar <<EOF2
d 121 .git
d 144 .github
s 100 .some.symlink
f 81 .whey
EOF2

$ test_ioccc/try_walk_set -s 2 -v 3 < bar
```

Also try:

```sh
$ test_ioccc/try_fts_walk -s 2 -v 3 test_ioccc/workdir/good/12345678-1234-4321-abcd-1234567890ab-3
```

You will see that the `walk_rule_set_txzchk[]` array is doing the job.

**Suggestion**: Before suggesting that there is a problem/bug with  the tables in `soup/walk_tbl.c`, demonstrate the problem/bug with   `test_ioccc/try_walk_set` tool, and the `test_ioccc/try_fts_walk` tool first.

**Suggestion**: Before modifying the tables in `soup/walk_tbl.c`, test with   `test_ioccc/try_walk_set` tool, and the `test_ioccc/try_fts_walk` tool first.

**Comment by lcn2** [comment]
> Okay but without the dot star change I made I get this:
> 
> ```
> txzchk required: Makefile not found
> txzchk required: prog.c not found
> txzchk required: remarks.md not found
> txzchk required: .auth.json not found
> txzchk required: .info.json not found
> txzchk found 2 prohibited items
>    prohibited file: test-1/.auth.json
>    prohibited file: test-1/.info.json
> Warning: txzchk: encountered an error walking directory in tarball: test_ioccc/test_txzchk/good/submit.test-1.1927515344.txt
> Warning: txzchk: test_ioccc/test_txzchk/good/submit.test-1.1927515344.txt: found 1 feather stuck in the tarball
> ```
> 
> In particular the lines that say prohibited. Or at least with your mods. Not sure which now. Also the files are actually there all of them. It seems like the directory is in the way but only some of the times. The above should not be happening. It is odd that it says it didn't find the files and then it found them and says they're not allowed.

Our guess is that you are **NOT** properly canonicalizing the paths you obtain from the tarball listing.  Because some filesystems are case independent, the proper args to `canon_path(3)` need to be passed.

The help call `canon_path(3)` in a consistent way that tools in this repo require (remember that `canon_path(3)` is generic and widely used, so you have to use it in the proper modes), use the `canonicalize_path()` function in `soup/walk_util.c` to call and use the `canon_path(3)` function.

For example:

```c
    struct walk_stat wstat;             /* walk_stat being processed */
    char const *path = NULL;    /* a path from a tarball line listing */
    char const *cpath = NULL;       /* canonicalized path arg as a string */
    enum path_sanity sanity = PATH_ERR_UNSET;       /* canonicalize_path() error code, or PATH_OK */
    size_t path_len = 0;            /* canonicalized path length */
    int_least32_t deep = -1;        /* canonicalized stack depth */
    
    ...

    cpath = canonicalize_path(&wstat, path, &sanity, &path_len, &deep);
    /* paranoia */
    if (cpath == NULL) {
        err(51, __func__, "canonicalize_path had an internal failure and returned NULL");
        not_reached();
    }
```

Use `test_ioccc/try_fts_walk` to test the `struct walk_set walk_txzchk`:


First run `make test` to build the proper test files:

```sh
$ make test
```

Then observe:

```sh
$ test_ioccc/try_fts_walk -s 2 -v 3 test_ioccc/workdir/good/12345678-1234-4321-abcd-1234567890ab-3
```

This produces:

```
debug[3]: set number WALK_SET_TXZCHK: 2
debug[3]: process: fts_path: .auth.json fts_name: .auth.json
debug[3]: process: fts_path: .info.json fts_name: .info.json
debug[3]: process: fts_path: makefile fts_name: makefile
debug[3]: process: fts_path: bar fts_name: bar
debug[3]: process: fts_path: extra1 fts_name: extra1
debug[3]: process: fts_path: extra2 fts_name: extra2
debug[3]: process: fts_path: foo fts_name: foo
debug[3]: process: fts_path: prog.alt.c fts_name: prog.alt.c
debug[3]: process: fts_path: prog.c fts_name: prog.c
debug[3]: process: fts_path: remarks.md fts_name: remarks.md
debug[3]: process: fts_path: topdir fts_name: topdir
debug[3]: process: fts_path: try.alt.sh fts_name: try.alt.sh
debug[3]: process: fts_path: try.sh fts_name: try.sh
debug[3]: test_walk: sorting walk_stat arrays by canonicalized path
debug[1]: txzchk walk was successful for: test_ioccc/workdir/good/12345678-1234-4321-abcd-1234567890ab-3
```

So as you can read above the "WALK_SET_TXZCHK" (i.e., `struct walk_set walk_txzchk` or `-s 2` in the test tool) **DOES** parse both `.auth.json` and `.info.json`:

```
debug[3]: process: fts_path: .auth.json fts_name: .auth.json
debug[3]: process: fts_path: .info.json fts_name: .info.json
```

Also observe this line:

```
debug[3]: process: fts_path: makefile fts_name: makefile
```

Notice that is reports **makefile** and **NOT** the Mixed Case **Makefile**.  This is because the canonicalization is passing `true` to the `lower_case` arg and thus the canonicalization is converting paths to lower case.

**Comment by xexyl** [comment]
> > The problem with this is it does not have the directory. If you have the directory it will give the errors I report in the above comment:
> > ```
> > $ test_ioccc/try_walk_set -s 2 -v 3 < foo
> > debug[3]: set number WALK_SET_TXZCHK: 2
> > debug[3]: process: fts_path: test-0/prog.c fts_name: prog.c
> > debug[3]: item[0]: txzchk should process: test-0/prog.c
> > debug[3]: process: fts_path: test-0/makefile fts_name: makefile
> > debug[3]: item[1]: txzchk should process: test-0/makefile
> > debug[3]: process: fts_path: test-0/remarks.md fts_name: remarks.md
> > debug[3]: item[2]: txzchk should process: test-0/remarks.md
> > debug[3]: prune and process: fts_path: test-0/.info.json fts_name: .info.json
> > debug[3]: item[3]: txzchk should ignore: test-0/.info.json
> > debug[3]: prune and process: fts_path: test-0/.auth.json fts_name: .auth.json
> > debug[3]: item[4]: txzchk should ignore: test-0/.auth.json
> > debug[3]: test_walk: sorting walk_stat arrays by canonicalized path
> > txzchk required: Makefile not found
> > debug[1]: txzchk required item[5]: Makefile not found
> > txzchk required: prog.c not found
> > debug[1]: txzchk required item[12]: prog.c not found
> > txzchk required: remarks.md not found
> > debug[1]: txzchk required item[17]: remarks.md not found
> > txzchk required: .auth.json not found
> > debug[1]: txzchk required item[20]: .auth.json not found
> > txzchk required: .info.json not found
> > debug[1]: txzchk required item[21]: .info.json not found
> > txzchk found 2 prohibited items
> >    prohibited file: test-0/.auth.json
> >    prohibited file: test-0/.info.json
> > debug[1]: txzchk some walk errors were detected
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now if I have to remove the first directory fine but that's not how it's been before and it might require a new function to do so. But this is the problem. This is different from before. That directory might or might not be in the way.
> > Please advise.
> 
> You appear to not be canonicalizing the with the proper topdir. The "`test-0/`" is **ABOVE** the top directory. For a tarball such as `test_ioccc/workdir/good/submit.test-5.1761855901.txz`, the leading "`test-5/`" needs to be skipped over before canoncailzating the rest of the path.

Yes as I thought. I probably did forget something simple (as you suggest). I did (it) early morning some day this week. I don't even know when exactly that was. I'll play with it either tomorrow or on the weekend. Thanks.

**Comment by lcn2** [comment]
> Perhaps what is needed is a function that strips off the first directory if a `/` is found? The only other thing I can think of is to change the levels but that would cause problems for other tools too.
> 
> Since you might have other ideas for it maybe you would like to do it? I seem to recall at one point dir_name() had an option to strip off specific components. I think I added that but that was during the rush to get to IOCCC28. Today I don't feel up to doing anything else anyway. I hope tomorrow is better but tomorrow I have to attend to something else so it seems unlikely.

For tarball listings generated via the `mkiocccentry(1)` tool process, the leading directory needs to be checked.  I.e., the `txzchk(1)` **MUST** verify that the leading directory from the tarball listing line is proper.  As part of this "is proper" check, you know where the leading directory ends.  So just pass a pointer to the character following the leading directory.

For example with the tarball listing line:

```
-r--r--r--  0 501    20       1856 Oct 30 13:25 12345678-1234-4321-abcd-1234567890ab-1/Makefile
````

The "`12345678-1234-4321-abcd-1234567890ab-1/`" is a valid first directory, so pass the address of the character after the "/" which in the above example, will be the address of the "`M`" to the `canonicalize_path()` function call and use the non-NULL return as the canonicalized path to pass to `record_step()`.

We hope this helps.

**Comment by xexyl** [comment]
> > I'll sleep on this but whether I get to do anything tomorrow or not I do not know. If not I'm sure I can look at it Saturday. Have a great rest of your day.
> 
> See the update to [GH issuecomment-3470105391](https://github.com/ioccc-src/mkiocccentry/issues/1325#issuecomment-3470105391).

I already do validate the directory. But it seems like there might be something new required too. I'll take a look when I'm back at it. Thanks for letting me know about the update.

**Comment by lcn2** [comment]
> Oh before I forget ... I might have missed something before: not sure if I did or did not but better ask. When I tally the total size: do I need to compare it to `MAX_SUM_FILELEN`? As in... `total_size > MAX_SUM_FILELEN`?
> 
> If not which macro should I compare it to?

The walk code sets the length limits (and the depth limits, etc.) when you call the `init_walk_stat()` function.  Those limits are consulted when `record_step()` is called.  The overall walk results are examined when `chk_walk()` is called.

**Comment by xexyl** [comment]
> > > > Oh before I forget ... I might have missed something before: not sure if I did or did not but better ask. When I tally the total size: do I need to compare it to `MAX_SUM_FILELEN`? As in... `total_size > MAX_SUM_FILELEN`?
> > > > If not which macro should I compare it to?
> > > 
> > > 
> > > The walk code sets the length limits (and the depth limits, etc.) when you call the `init_walk_stat()` function. Those limits are consulted when `record_step()` is called. The overall walk results are examined when `chk_walk()` is called.
> > 
> > 
> > I meant file size recorded in the tar(1) output.
> 
> As was stated elsewhere, as you parse tarball listing lines, just keep a running sum of the parsed sizes. When when you run out of tarball listing lines, so something like:
> 
>     if (total_size > MAX_SUM_FILELEN) {
>         dbg(DBG_LOW, "total length of tarball contents is too long: %zu > limit: %zu", (long long) total_size, (long long) MAX_SUM_FILELEN);
>         ... report on the problem of too much tarball content ...
>     } else {
>         dbg(DBG_LOW, "total length of tarball size: %zu <= limit: %zu", (long long) total_size, (long long) MAX_SUM_FILELEN);
>     }

Yup although I will do that after parsing the total length so that it won't be repeated. I might have missed that last time: not sure. Thanks for confirming the macro.

**Comment by xexyl** [comment]
Done with that at least. I have to do the other stuff of course. Not sure when that will be done.

**Comment by xexyl** [comment]
... about to commit .. running make prep first ....

**Comment by xexyl** [comment]
Unless I am very much mistaken commit https://github.com/ioccc-src/mkiocccentry/pull/1332/commits/1381af18d0299bebb6c74cb7bde8a9a2740828ba has resolved this issue! It also has a few minor fixes and things that we discussed this week (and maybe a few last week .. not sure).

I will possibly look a bit at the mkiocccentry today but if it doesn't happen soon that is highly unlikely.

**Comment by lcn2** [comment]
With commit ce72858075c1f7184e8d0711b295a709e280d043 this issue looks at first glance to be close to being resolved.

Thank you @xexyl 

We continue to review that above mentioned important commit.

**Comment by xexyl** [comment]
> With commit ce72858075c1f7184e8d0711b295a709e280d043 this issue looks at first glance to be close to being resolved.
> 
> Thank you @xexyl 
> 
> We continue to review that above mentioned important commit.

Let me know if I missed anything and I will be happy to finish it! Probably not today but it does seem good and hopefully I did get everything in order.

**Comment by lcn2** [comment]
> > With commit [ce72858](https://github.com/ioccc-src/mkiocccentry/commit/ce72858075c1f7184e8d0711b295a709e280d043) this issue looks at first glance to be close to being resolved.
> > Thank you [@xexyl](https://github.com/xexyl)
> > We continue to review that above mentioned important commit.
> 
> Let me know if I missed anything and I will be happy to finish it! Probably not today but it does seem good and hopefully I did get everything in order.

We are adding some new test cases.

And perhaps not the "fault of" recent commits, we have at least one case where some "feathers" may have been able to be slipped under the nose of `txzchk(1)`.  So stay tuned for a commit that adds some test cases.

**Comment by xexyl** [comment]
> > > With commit [ce72858](https://github.com/ioccc-src/mkiocccentry/commit/ce72858075c1f7184e8d0711b295a709e280d043) this issue looks at first glance to be close to being resolved.
> > > Thank you [@xexyl](https://github.com/xexyl)
> > > We continue to review that above mentioned important commit.
> > 
> > 
> > Let me know if I missed anything and I will be happy to finish it! Probably not today but it does seem good and hopefully I did get everything in order.
> 
> We are adding some new test cases.
> 
> And perhaps not the "fault of" recent commits, we have at least one case where some "feathers" may have been able to be slipped under the nose of `txzchk(1)`. So stay tuned for a commit that adds some test cases.

It would be useful to see the output too. But I'll have to look tomorrow. Way too tired today and soon I'll be doing some cooking as well (roasting the last tomatoes from this year's crop).

Thanks and please let me know.

**Comment by xexyl** [comment]
Ah. Somehow I removed some of those checks with the new set up. I will take a look hopefully tomorrow morning. 

Thanks.

**Comment by xexyl** [comment]
I once wrote a function that checks for the wrong chars in the permission string ... can't find it .... once I find it or just rewrite it (could have been done quickly if I had) I can do the ACL one ... think I have everything else. But I can't deal with that at this precise moment.  Unless I have missed something I will have everything after that which should be later today.

**Comment by xexyl** [comment]
No .. I take that back. There are other things too ... I see you made another comment. This might take more time then.

**Comment by xexyl** [comment]
> 
> Look over the new tests (both good and bad) to be sure that the test results are OK.
> 
> From what we can see, most of the new tests seem OK except for:
> 
> Fix: `submit.12345678-1234-4321-abcd-1234567890ab-8.1761934327.txt.err`
> 
> The output should **NOT** be empty due to a negative file length.
> 
> Review: `submit.12345678-1234-4321-abcd-1234567890ab-7.1761934326.txt.err`
> 
> Is the "_Warning: string_to_intmax: error converting string_" the best way to handle "super-bogus" lengths? Maybe it is OK?
> 

I am not sure how else it would work and since it flags the tarball (though also because of a missing Makefile) I'm not sure why it should be an issue as is?

The others will be fixed (I think) when I add back that function that checks for bogus chars in the permission string. However a space I'm not sure how that's going to be detected as how can it: strtok_r() with tab and spaces will just skip that over.

The others including perm 0000 (which I already checked as of a bit ago) will be just fine.

**Comment by xexyl** [comment]
Minus count of feathers the negative file size issue is resolved ... but I must leave for a while. I think the other issue, the invalid perms string, is also resolved although I might add an extra sanity check just to be sure.

It is not clear to me how long I'll be gone but I should be able to finish this today: barring the Vogons or something like that ...

**Comment by lcn2** [comment]
With commit 2986d9d2b78129a47aae8d1db946f87567cab1ec this issue is closed 👍

Thank you @xexyl 🙏

**Comment by xexyl** [comment]
> > These things were removed with the walk code .. the question is does the walk code pick up on this? I guess not. But that means that I do have to have some of the functions return. I feared something wasn't right here .. wish I hadn't removed them. I guess I just have to simplify them. I haven't pulled the changes from the repo to the server so I can save them more easily and then add them back.
> 
> We thought about adding permissions to the table-drive walk code .. that could be done pre-**IOCCC30**.

Well I could do this too: just make sure that it's not FTS_NS (no stat available). This would be done for each list of files/directories. But this would not help with txzchk of course. 

BTW: **_course_** is an anagram for **_O curse_**!

**Comment by xexyl** [comment]
> With commit [2986d9d](https://github.com/ioccc-src/mkiocccentry/commit/2986d9d2b78129a47aae8d1db946f87567cab1ec) this issue is closed 👍
> 
> Thank you [@xexyl](https://github.com/xexyl) 🙏

You are most welcome! Now just one more pre-IOCCC29! mkiocccentry changes. I hope to start on it today but I am totally knackered. Still I am usually feeling that way until a couple hours from now so that might be okay. Tomorrow, if I have the energy, minus a call I have to take, I should have more time than usual.

I will check the issue soon I hope and maybe start changing the mechanics of the three main functions: the scan_topdir() would be like before but instead of passing the topdir it would pass the walk struct (obviously a pointer to it).
